export const categories = [
  "Desenvolvimento Web",
  "Desenvolvimento Mobile",
  "Desenvolvimento de Jogos",
  "Programação de Sistemas",
  "Scripting e Automação",
  "Ciência de Dados e Machine Learning",
  "Linguagens de Consulta de Banco de Dados",
  "Sistemas Embarcados e IoT",
  "Programação Funcional",
  "Blockchain e Smart Contracts",
  "Cloud e DevOps",
  "Computação Científica",
];

export const technologies = [
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Rust",
  "JavaScript",
  "TypeScript",
  "PHP",
  "Ruby",
  "HTML",
  "CSS",
  "Swift",
  "Kotlin",
  "Dart",
  "Lua",
  "GDScript",
  "Assembly",
  "Bash",
  "PowerShell",
  "R",
  "Julia",
  "SQL",
  "PL/SQL",
  "MicroPython",
  "Haskell",
  "Elixir",
  "F#",
  "Lisp",
  "Solidity",
  "Go",
  "YAML",
  "Terraform",
  "Fortran",
];
